version: "3.8"

services:
  sql-query-test-1:
    image: postgres:15
    container_name: sql-query-test-1
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: company
    ports:
      - "5432:5432"
    volumes:
      - ./sql-query-test-1/init-db:/docker-entrypoint-initdb.d

  sql-query-test-2:
    image: postgres:15
    container_name: sql-query-test-2
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: company
    ports:
      - "5434:5432"
    volumes:
      - ./sql-query-test-2/init-db:/docker-entrypoint-initdb.d

  mongo-query-test-3:
    image: mongo:6
    container_name: mongo-query-test-3
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-query-test-3/init-db/init.js:/docker-entrypoint-initdb.d/init.js:ro
